# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Projects < Formula
  desc "Manage project scaffolds from the command line"
  homepage "https://github.com/jackmorganxyz/projectsCLI"
  version "0.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.11/projects_0.0.11_darwin_amd64.tar.gz"
      sha256 "fac860916fb074f421b5d505f5df708c03af5fa3add2ab32cb26d362f839f5c9"

      define_method(:install) do
        bin.install "projects"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.11/projects_0.0.11_darwin_arm64.tar.gz"
      sha256 "b16b2624dbac49d914dfa450331024fd8779fa7b93d2725ab31ab308ac552aab"

      define_method(:install) do
        bin.install "projects"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.11/projects_0.0.11_linux_amd64.tar.gz"
      sha256 "d2e754cbdc458787d8e40d278cae52436128826cfff1eaf62e943cb0429f13bd"
      define_method(:install) do
        bin.install "projects"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.11/projects_0.0.11_linux_arm64.tar.gz"
      sha256 "0d3b9de6745bfcac0fe2bc9b06206b89932b5a0c2fc17ed4951ce3ddc942a7d9"
      define_method(:install) do
        bin.install "projects"
      end
    end
  end

  test do
    system "#{bin}/projects", "--version"
  end
end
