# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Projects < Formula
  desc "Manage project scaffolds from the command line"
  homepage "https://github.com/jackmorganxyz/projectsCLI"
  version "0.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.12/projects_0.0.12_darwin_amd64.tar.gz"
      sha256 "e1e1b30bfc2a4f8c22049704068bc6b019676202bee5aa86e1161fbc0ddb2922"

      define_method(:install) do
        bin.install "projects"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.12/projects_0.0.12_darwin_arm64.tar.gz"
      sha256 "013f2a0e0765648945910965a4dec627a604de9f544bc4a40c49dafbf79b9f90"

      define_method(:install) do
        bin.install "projects"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.12/projects_0.0.12_linux_amd64.tar.gz"
      sha256 "654ce7246d870ce9f20621704fabaf8874a03846df43b54abf7a1484f27e42ff"
      define_method(:install) do
        bin.install "projects"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.12/projects_0.0.12_linux_arm64.tar.gz"
      sha256 "62ef6a3161e9dbf7c5abd6fa9efeab92be1c86df7e6f5d945b632954adfd423b"
      define_method(:install) do
        bin.install "projects"
      end
    end
  end

  test do
    system "#{bin}/projects", "--version"
  end
end
