# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Projectscli < Formula
  desc "Manage project scaffolds from the command line"
  homepage "https://github.com/jackmorganxyz/projectsCLI"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.4/projectsCLI_0.0.4_darwin_amd64.tar.gz"
      sha256 "57f8cec69906ed02cc40b25319a130f726f1756e9fac3da3b5745674bb77e563"

      define_method(:install) do
        bin.install "projectsCLI"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.4/projectsCLI_0.0.4_darwin_arm64.tar.gz"
      sha256 "12e7ad1b4ec6ee9b5d2c481e88a349c8694449b8bf650100e509a497cda5ea9e"

      define_method(:install) do
        bin.install "projectsCLI"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.4/projectsCLI_0.0.4_linux_amd64.tar.gz"
      sha256 "01e89ba6110eb40023f10a364e984e7c17aa24e6a920745bfe455037633329a7"
      define_method(:install) do
        bin.install "projectsCLI"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.4/projectsCLI_0.0.4_linux_arm64.tar.gz"
      sha256 "5384ddaab184ce0ae0988e63d67c63a6a53088ea7187a5bc9d3952b3dc34088a"
      define_method(:install) do
        bin.install "projectsCLI"
      end
    end
  end

  test do
    system "#{bin}/projectsCLI", "--version"
  end
end
