# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Projectscli < Formula
  desc "Manage project scaffolds from the command line"
  homepage "https://github.com/jackmorganxyz/projectsCLI"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.8/projects_0.0.8_darwin_amd64.tar.gz"
      sha256 "1e2658ae5b0dc84de113e3e4033d2951f79753167746b6423b411098fbab5535"

      define_method(:install) do
        bin.install "projects"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.8/projects_0.0.8_darwin_arm64.tar.gz"
      sha256 "45aa2c16f001e01365437a0d81e581f3cab960e53484d4deb0a52f855232766f"

      define_method(:install) do
        bin.install "projects"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.8/projects_0.0.8_linux_amd64.tar.gz"
      sha256 "f6e7ff64c5425fafc30bd448c1dfa9062f74ca2880b86020a3c274ba0fa30f63"
      define_method(:install) do
        bin.install "projects"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.8/projects_0.0.8_linux_arm64.tar.gz"
      sha256 "3058fe94794547006256c5515f896c14ef266b4565b4d2e37690aa6c23a303e4"
      define_method(:install) do
        bin.install "projects"
      end
    end
  end

  test do
    system "#{bin}/projects", "--version"
  end
end
