# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Projects < Formula
  desc "Manage project scaffolds from the command line"
  homepage "https://github.com/jackmorganxyz/projectsCLI"
  version "0.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.10/projects_0.0.10_darwin_amd64.tar.gz"
      sha256 "f8b8dec16d1db493057df2362e0f2c395e47964014125f4818ffff5804608719"

      define_method(:install) do
        bin.install "projects"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.10/projects_0.0.10_darwin_arm64.tar.gz"
      sha256 "f1baef0fe051c7323fef4a37aa902d208eaed06109a9d513348f45db717e42ec"

      define_method(:install) do
        bin.install "projects"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.10/projects_0.0.10_linux_amd64.tar.gz"
      sha256 "87fbf27e38720405201a2594caa62c0f4d405e2216266a9dbc6f6eed330000ad"
      define_method(:install) do
        bin.install "projects"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jackmorganxyz/projectsCLI/releases/download/v0.0.10/projects_0.0.10_linux_arm64.tar.gz"
      sha256 "2c0d2645b42cd56fe1b57e4cf8d719bb7a6c94deede26c72b14b1fa7a3e662cd"
      define_method(:install) do
        bin.install "projects"
      end
    end
  end

  test do
    system "#{bin}/projects", "--version"
  end
end
